### ISSUE TITLE
Language id?

### ISSUE THREAD

**Issue by SF-300** [SJrX/systemdUnitFilePlugin#113]
Hi!

First of all - thanks for the great work to all the contributors!

I have a small question: how to determine the language id to be used for injection comments? E.g.:
```
# language=???
content = f"""\
[Match]
Name=enp1s0f*

[Network]
Bridge=${bridge_iface_name}
"""
```
What should I write instead of `???`? I wasn't able to find this information neither in the IDE's configs, nor glancing through this repository...

Any help would be greatly appreciated! Thanks in advance!

**Comment by SJrX** [comment]
Thank you. 

You know I actually had this same problem with another plugin recently and it's only because I'm a plugin developer that I could figure it out. 

I'm in vacation right now, but give the following a try:

"Unit File (systemd)"

It's possible that that doesn't work because of spaces and there is no way to do a language injection presently. I could probably patch out a new version if that is the case and fix it.

**Comment by SJrX** [comment]
Looks like it doesn't work directly
![image](https://user-images.githubusercontent.com/1916599/127748839-802bab7a-6522-4c32-ab45-519943a8ccb0.png)

**Comment by SJrX** [comment]
Actually this works:

![image](https://user-images.githubusercontent.com/1916599/127749098-33cb783f-cf72-47eb-912e-aa2d56a8a243.png)

**Comment by SJrX** [comment]
Created the following bugs against IDEA

https://youtrack.jetbrains.com/issue/IDEA-274995
https://youtrack.jetbrains.com/issue/IDEA-274994

Closing, let me know if you have any problems @SF-300 .
