### ISSUE TITLE
Not working with Goland anymore

### ISSUE THREAD

**Issue by 0xjac** [SJrX/systemdUnitFilePlugin#128]
The plugin was working fine previously. I have noticed it marked as incompatible with Goland 2022.1.

Error message:

> Plugin error
> Plugin 'Unit File Support (systemd)' (version '0.3.4') is not compatible with the current version of the IDE, because it requires build 221.0 or older but the current build is GO-221.5080.224

This also shows on the JetBrains Marketplace:

![2022-04-25-170325_2536x566_scrot](https://user-images.githubusercontent.com/2848217/165117041-08ec358f-0878-4a91-969f-1dc4afb65d2a.png)

Goland version:
```
GoLand 2022.1
Build #GO-221.5080.224, built on April 13, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.16.14-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    debugger.watches.in.variables=false
    suggest.all.run.configurations.from.context=true
    ide.completion.variant.limit=500
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    org.toml.lang (221.5080.126)
    ru.sadv1r.ansible-vault-editor-idea-plugin (1.17)
    me.serce.solidity (2.3.8)
    com.vincentp.gruvbox-theme (0.5.4)
    com.jetbrains.plugins.ini4idea (221.5080.126)
    cc.duduhuo.git-conflict (1.0.4)
    YAML/Ansible support (0.11.2)
    org.rust.lang (0.4.169.4584-221)
    dev.blachut.svelte.lang (0.22.0)
    NodeJS (221.5080.169)

Current Desktop: i3
```

**Comment by 0xjac** [comment]
Wow, thanks for the quick reply @SJrX 

I've tried downloading and installing the plugin (version 0.3.5) manually as you suggested. Sadly I get a popup with a similar error:

> Plugin 'Unit File Support (systemd)' (version '0.3.5') is not compatible with the current version of the IDE, because it requires build 221.5080.210 or older but the current build is GO-221.5080.224

I'm not familiar with the internal of JetBrains plugins but I am happy to help, when you have the time. No rush!

If it helps, I'm on linux (Manjaro) and I've installed Goland (and the `goland-jre`) via AUR as specified [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=goland). I am not sure if this has an effect. I have other plugins and they all seem to work fine.

Let me know if you need any info or if you want me to test anything.

**Comment by SJrX** [comment]
My guess is that in upper bound set in #126 / #127 was way too tight. We will see if this fixes it.

**Comment by 0xjac** [comment]
Thanks for the fix @SJrX, I'll test it as soon as I see it popup on the JetBrains Marketplace! :muscle:

**Comment by SJrX** [comment]
I uploaded the build to https://github.com/SJrX/systemdUnitFilePlugin/releases/tag/v0.3.6 so you can try just [Installing a plugin from Zip -- GoLand Documentation](https://www.jetbrains.com/help/go/managing-plugins.html#install_plugin_from_disk) if you don't want to wait. It would help me as well, since I haven't had time to actually replicate this and this is just a shot in the dark.

**Comment by SJrX** [comment]
@0xjac , I uploaded the build to https://github.com/SJrX/systemdUnitFilePlugin/releases/tag/v0.3.6 so you can try just [Installing a plugin from Zip -- GoLand Documentation](https://www.jetbrains.com/help/go/managing-plugins.html#install_plugin_from_disk) if you don't want to wait (however those releases don't go through JetBrains verification which means it's slightly riskier for you). It would help me as well, since I haven't had time to actually replicate this and this is just a shot in the dark.

**Comment by 0xjac** [comment]
@SJrX damn I missed that. I downloaded and installed it. It all works fine: I have syntax highlighting and code completion just like before! Thanks again for the fix.

Let me know if you want me to test anything specific.

**Comment by SJrX** [comment]
You didn't miss anything, I just uploaded it now after your comment and forgot the last few releases :) 

Cheers.
