### ISSUE TITLE
Tab characters in values are not supported

### ISSUE THREAD

**Issue by twogood** [SJrX/systemdUnitFilePlugin#51]
Nice plugin, thanks! I just discovered this minor thing. Where in the source would I find the relevant code if I were to try to make a PR?

![image](https://user-images.githubusercontent.com/189982/50485335-2aba4a00-09f5-11e9-969f-08920888f545.png)

**Comment by SJrX** [comment]
Thank you, it is glad to know that someone found it useful:

Continuations are in fact supported, and there are several unit tests for it: 
`net.sjrx.intellij.plugins.systemdunitfiles.parser.UnitFileParserTest#testLineContinuationSimple`
`net.sjrx.intellij.plugins.systemdunitfiles.parser.UnitFileParserTest#testLineContinuationWithKeys`
`net.sjrx.intellij.plugins.systemdunitfiles.parser.UnitFileParserTest#testLineContinuationWithComment`.

So it isn't simply a matter of adding support for it. As to where the bug is I don't have an immediate answer to as I'm on vacation. (Background: this plugin was meant to help familiarize myself with IntelliJ Plugin development, so I'm not an expert and it has been a few months since I looked at it).

I don't think there is enough information based on the symptom to know exactly where the bug is. The first thing I would need to look at is what the parse tree of the file is because that would narrow it down. 

I just glanced at the lexer definition `net/sjrx/intellij/plugins/systemdunitfiles/lexer/SystemdUnitFile.flex ` and I'm not sure how this would happen. 

I guess I have some questions for you:
1) are you on Mac or Windows or Linux? 
2) What are the line endings in the file? (Could you attach a file and also make an md5 of your system (in case of encoding changes))
3) Is there any white space after the \ on line 7?  (If that was the problem then an inspection for that should be trivial and easy to do).

Finally a word of warning is that even though it's a relatively small and new project, I was not happy with how the lexer and parser turned out, and the advise I got was to drastically change them (i.e., allow the lexer and parser to tolerate way more badness and then use inspections to highlight).

**Comment by twogood** [comment]
Thanks for the comprehensive response!

After some experimenting, I now suspect that this is caused by the is using tabs, not spaces, for the indent on the continuation lines in the file, and this is likely because I copied the lines from a Makefile. (I'd never use tabs otherwise, I promise!)

1. I'm on Linux
2. LF only
3. No whitespaces after either backslash

I've cloned the code now and will play with the test cases!

**Comment by twogood** [comment]
I can't deduct how to adjust the lexer or grammar to solve this, but now I can change to spaces in my `.service` file to get rid of the error in the IDE :)

**Comment by SJrX** [comment]
Yeah it will have a tab. But what is happening is that it doesn't recognize the continuation in this case and thinks a new key is starting.I'm out and about right now. I will look at this issue over the next couple of weeks if you want. I don't think the fix will be easy as a lot of that stuff is tin cans and strings. 

Also not helping is that systemds format isnt formally defined anywhere so I need to check what it will do as well.

**Comment by twogood** [comment]
Fix it if you feel like fixing it :)
