### ISSUE TITLE
IntelliJ hangs when updating to new systemdUnitFilePlugin

### ISSUE THREAD

**Issue by irvintim** [SJrX/systemdUnitFilePlugin#99]
On 2 different IntelliJ setups -- one running 2020.1.3 and one running 2020.2 (one on Ubuntu 20.04 and one on Windows 10) -- when they try to Update the "Unit File Support (systemd)" plugin the progress slider for "Downloading plugin 'Unit File Support (systemd)'" gets all the way to the end and then the entire application hangs.  The only solution is to kill it (either with "kill" or  the Task Manager) depending on the system.
Once I kill off the app and restart then the update works.

**Comment by SJrX** [comment]
Hrm that isn't good. I don't have any Windows or Ubuntu setups, but I have a bunch of Arch Linux setups, and I've gotten it downloaded about 3 times now and I can't reproduce the issue. 

Additionally at a guess, I don't think the plugin is doing anything at that point. As far as plugins go, the systemd plugin is very simple and so should be easy to reload. IntelliJ 2020.1 added the new capability to dynamically reload plugins, and so my guess would be the issue is with that. 

If you could maybe see if you could reproduce the issue and the next time it hangs follow the [instructions here](https://intellij-support.jetbrains.com/hc/en-us/articles/206544899-Getting-a-thread-dump-when-IDE-hangs-and-doesn-t-respond) for a thread dump (or check if you have any existing ones) in the logs directory that would be useful, additionally some logs might have some light. It also links to [how to get access to the logs.](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085)

:warning: logs potentially contain very sensitive things in them, and I'm super paranoid about giving people logs. Depending on the plugins you are using and the capability, you might have given the IDE some SSH keys, database passwords, AWS/Azure keys, who knows what. I occasionally will give a company them, but you should be cautious about giving logs to some dirtbag on github like me :smile: 

(thread dumps are mostly safe).

**Comment by SJrX** [comment]
Stale, please reopen if you are still having issues.
